### 회원 가입
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "login_id": "aaaaaa",
  "nickname": "nic",
  "password": "1234",
  "confirm": "1234",
  "pet_name": "nabi"
}

### 로그인
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "login_id": "aaaaaa",
  "password": "1234"
}

### 로그 아웃
DELETE http://localhost:3000/api/logout

### 회원 탈퇴
DELETE http://localhost:3000/api/signout
Content-Type: application/json

{
  "password": "1234"
}